echo "----------------------------------------------------------------"
echo "| Select Any Option                                            |"
echo "| 1. Want to see whole database                                |"
echo "| 2. Want to see information of any particular player          |"
echo "| 3.Add information about any player                           |" 
echo "| 4.Delete the information about any player                    |"
echo "| 5.Want scrap information from website in detail of any player|"
echo "| 6.Exit                                                       |"
echo "----------------------------------------------------------------"
